// WebSocket server URL
const API_URL_DEVELOPMENT = "ws://localhost:8000";
const API_URL_PRODUCTION = "wss://pokerpocket.nitramite.com";

// UI settings
const LS_MODE_TOGGLE_STATE = "LS_MODE_TOGGLE_STATE";
const LS_ENABLE_SOUNDS_STATE = "LS_ENABLE_SOUNDS_STATE";

// For log in user's
const LS_POLICY_ACCEPTED = "LS_POLICY_ACCEPTED";
const LS_LOGGED_IN = "LS_LOGGED_IN";
const LS_USERNAME = "LS_USERNAME";
const LS_PASSWORD = "LS_PASSWORD";
const LS_USE_BLACK_CARDS = "LS_USE_BLACK_CARDS";
const LS_USE_PURPLE_TABLE = "LS_USE_PURPLE_TABLE";
